EvaluationArguments:
  batch_size: 16
  decimal_points: -1
  float32: false
  load_from_raw: true
  max_sequence_length: 250
  max_token_length: 256
  max_val_samples: none
  model_dir: /scratch/project_465001749/eleznyto/t5-slt/T5_for_SLT/results/5-1-YT-ASL-split_constant0.001/checkpoint-12500
  model_name: T5_YTASL_predict
  output_dir: ./results
  skip_frames: false
  split: test
  paraphrase_mode: min_loss   # none | random | min_loss
ModelArguments:
  base_model_name: google/t5-v1_1-base
  early_stopping: false
  length_penalty: 0.6
  max_length: 128
  no_repeat_ngram_size: 0
  num_beams: 5
  sign_input_dim: 208
SignDataArguments:
  annotation_path:
    test: How2Sign/H2S.annotations.test.json
  data_dir: /scratch/project_465001749/data/
  visual_features:
    dino:
      enable_input: false
      test: How2Sign/features/dino/h2s.dino.test.json
    mae:
      enable_input: false
      test: How2Sign/features/mae/h2s.mae.test.json
    pose:
      augmentation_type: none
      enable_input: true
      interpolate: -1
      missing_values: -10
      normalization:
        data_key: cropped_keypoints
        normalization_method: sign_space
        test_json_dir: /scratch/project_465001749/data/How2Sign/data/test/raw_keypoints
      test: How2Sign/features/keypoints/h2s.keypoints.test.json
    sign2vec:
      enable_input: false
      test: How2Sign/features/sign2vec/h2s.sign2vec.test.json
SignModelArguments:
  projectors:
    dino:
      dim: 1152
    mae:
      dim: 768
    pose:
      dim: 208
    sign2vec:
      dim: 768
